services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmsdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tmsdb
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

